OCAML=ocamlopt
OCAMLFLAGS= -I +sdl -I +site-lib/sdl
OCAMLLD= bigarray.cmxa sdl.cmxa sdlloader.cmxa
 
tpsdl: tpsdl.ml
	${OCAML} ${OCAMLFLAGS} ${OCAMLLD} -o tpsdl tpsdl.ml
 
clean::
	rm -f *~ *.o *.cm? tpsdl